///////////////////////////////////////////////////////////////////////////////////////////////
//
//    This File is Part of the CallButler Open Source PBX (http://www.codeplex.com/callbutler
//
//    Copyright (c) 2005-2008, Jim Heising
//    All rights reserved.
//
//    Redistribution and use in source and binary forms, with or without modification,
//    are permitted provided that the following conditions are met:
//
//    * Redistributions of source code must retain the above copyright notice,
//      this list of conditions and the following disclaimer.
//
//    * Redistributions in binary form must reproduce the above copyright notice,
//      this list of conditions and the following disclaimer in the documentation and/or
//      other materials provided with the distribution.
//
//    * Neither the name of Jim Heising nor the names of its contributors may be
//      used to endorse or promote products derived from this software without specific prior
//      written permission.
//
//    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
//    ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
//    WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
//    IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
//    INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
//    NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
//    PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
//    WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
//    ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
//    POSSIBILITY OF SUCH DAMAGE.
//
///////////////////////////////////////////////////////////////////////////////////////////////

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallButler.Manager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CallButler.Manager.Properties.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephony2 Corporation. All Rights Reserved.
        /// </summary>
        internal static string AboutForm_CopyrightPostfix {
            get {
                return ResourceManager.GetString("AboutForm_CopyrightPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This software trial has expired and is unlicensed.
        /// </summary>
        internal static string AboutForm_Expired {
            get {
                return ResourceManager.GetString("AboutForm_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Trial license expires on {0}.
        /// </summary>
        internal static string AboutForm_ExpiresOn {
            get {
                return ResourceManager.GetString("AboutForm_ExpiresOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This software is licensed free of charge.
        /// </summary>
        internal static string AboutForm_FreeLicense {
            get {
                return ResourceManager.GetString("AboutForm_FreeLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensed to: {0}.
        /// </summary>
        internal static string AboutForm_LicensedTo {
            get {
                return ResourceManager.GetString("AboutForm_LicensedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Version {0}.
        /// </summary>
        internal static string AboutForm_ManagerVersion {
            get {
                return ResourceManager.GetString("AboutForm_ManagerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Version {0}.
        /// </summary>
        internal static string AboutForm_ServerVersion {
            get {
                return ResourceManager.GetString("AboutForm_ServerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new option....
        /// </summary>
        internal static string CallFlowView_AddNewOption {
            get {
                return ResourceManager.GetString("CallFlowView_AddNewOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-on Module.
        /// </summary>
        internal static string CallFlowView_AddonModule {
            get {
                return ResourceManager.GetString("CallFlowView_AddonModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Remove Languages....
        /// </summary>
        internal static string CallFlowView_AddRemoveLanguages {
            get {
                return ResourceManager.GetString("CallFlowView_AddRemoveLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer an incoming call.
        /// </summary>
        internal static string CallFlowView_AnswerCall {
            get {
                return ResourceManager.GetString("CallFlowView_AnswerCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask the caller to choose a language.
        /// </summary>
        internal static string CallFlowView_AskChooseLanguage {
            get {
                return ResourceManager.GetString("CallFlowView_AskChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The caller dials an option.
        /// </summary>
        internal static string CallFlowView_CallerDials {
            get {
                return ResourceManager.GetString("CallFlowView_CallerDials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings....
        /// </summary>
        internal static string CallFlowView_CallSettings {
            get {
                return ResourceManager.GetString("CallFlowView_CallSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change....
        /// </summary>
        internal static string CallFlowView_Change {
            get {
                return ResourceManager.GetString("CallFlowView_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Language.
        /// </summary>
        internal static string CallFlowView_ChooseLanguage {
            get {
                return ResourceManager.GetString("CallFlowView_ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this department?.
        /// </summary>
        internal static string CallFlowView_ConfirmDeleteDepartment {
            get {
                return ResourceManager.GetString("CallFlowView_ConfirmDeleteDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute a Custom Script.
        /// </summary>
        internal static string CallFlowView_CustomScript {
            get {
                return ResourceManager.GetString("CallFlowView_CustomScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dial {0} for {1}.
        /// </summary>
        internal static string CallFlowView_Dial {
            get {
                return ResourceManager.GetString("CallFlowView_Dial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dial an Option.
        /// </summary>
        internal static string CallFlowView_DialAnOption {
            get {
                return ResourceManager.GetString("CallFlowView_DialAnOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explain the available options.
        /// </summary>
        internal static string CallFlowView_ExplainOptions {
            get {
                return ResourceManager.GetString("CallFlowView_ExplainOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension appears to have been deleted.
        /// </summary>
        internal static string CallFlowView_ExtDeleted {
            get {
                return ResourceManager.GetString("CallFlowView_ExtDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For {0}, press {1}.
        ///
        ///.
        /// </summary>
        internal static string CallFlowView_ForDepartment {
            get {
                return ResourceManager.GetString("CallFlowView_ForDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For a company directory, press pound.
        ///
        ///To repeat this menu, press star..
        /// </summary>
        internal static string CallFlowView_ForDirectory {
            get {
                return ResourceManager.GetString("CallFlowView_ForDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you know your party&apos;s extension, you may dial it at any time.
        ///
        ///.
        /// </summary>
        internal static string CallFlowView_KnowParty {
            get {
                return ResourceManager.GetString("CallFlowView_KnowParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since you have made changes to your language options, it is recommended that you update your Choose a Language Greeting to reflect these changes..
        /// </summary>
        internal static string CallFlowView_LanguageChanges {
            get {
                return ResourceManager.GetString("CallFlowView_LanguageChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        ///
        ///.
        /// </summary>
        internal static string CallFlowView_MainMenu {
            get {
                return ResourceManager.GetString("CallFlowView_MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu Greeting.
        /// </summary>
        internal static string CallFlowView_MainMenuGreeting {
            get {
                return ResourceManager.GetString("CallFlowView_MainMenuGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since you have made changes to your menu options, it is recommended that you update your Main Menu Greeting to reflect these changes..
        /// </summary>
        internal static string CallFlowView_MenuOptionChanges {
            get {
                return ResourceManager.GetString("CallFlowView_MenuOptionChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Department.
        /// </summary>
        internal static string CallFlowView_NewDepartment {
            get {
                return ResourceManager.GetString("CallFlowView_NewDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick up the call....
        /// </summary>
        internal static string CallFlowView_PickUpCall {
            get {
                return ResourceManager.GetString("CallFlowView_PickUpCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play a Greeting.
        /// </summary>
        internal static string CallFlowView_PlayGreeting {
            get {
                return ResourceManager.GetString("CallFlowView_PlayGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer to Extension {0}.
        /// </summary>
        internal static string CallFlowView_TransferExt {
            get {
                return ResourceManager.GetString("CallFlowView_TransferExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer to {0}.
        /// </summary>
        internal static string CallFlowView_TransferNum {
            get {
                return ResourceManager.GetString("CallFlowView_TransferNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Extension.
        /// </summary>
        internal static string CallFlowView_UnknownExt {
            get {
                return ResourceManager.GetString("CallFlowView_UnknownExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome your caller.
        /// </summary>
        internal static string CallFlowView_WelcomeCaller {
            get {
                return ResourceManager.GetString("CallFlowView_WelcomeCaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Greeting.
        /// </summary>
        internal static string CallFlowView_WelcomeGreeting {
            get {
                return ResourceManager.GetString("CallFlowView_WelcomeGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to [Your Company Name].
        /// </summary>
        internal static string CallFlowView_WelcomeTo {
            get {
                return ResourceManager.GetString("CallFlowView_WelcomeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear the call history?.
        /// </summary>
        internal static string CallHistoryView_ConfirmClear {
            get {
                return ResourceManager.GetString("CallHistoryView_ConfirmClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find an Outlook contact that matches this caller. Would you like to create a new contact with this information?.
        /// </summary>
        internal static string CallHistoryView_ContactNotFound {
            get {
                return ResourceManager.GetString("CallHistoryView_ContactNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Contact Found.
        /// </summary>
        internal static string CallHistoryView_NoContactFound {
            get {
                return ResourceManager.GetString("CallHistoryView_NoContactFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing CallButler Edition. Please wait while the service restarts..
        /// </summary>
        internal static string Common_ChangingEdition {
            get {
                return ResourceManager.GetString("Common_ChangingEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Common_Close {
            get {
                return ResourceManager.GetString("Common_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        internal static string Common_ConfirmDelete {
            get {
                return ResourceManager.GetString("Common_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Common_Delete {
            get {
                return ResourceManager.GetString("Common_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit....
        /// </summary>
        internal static string Common_Edit {
            get {
                return ResourceManager.GetString("Common_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Error.
        /// </summary>
        internal static string Common_EmailError {
            get {
                return ResourceManager.GetString("Common_EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem sending an Email to {0}
        ///
        ///Please check your mail settings and try again.
        ///
        ///Error Detail:
        ///{1}.
        /// </summary>
        internal static string Common_EmailProblem {
            get {
                return ResourceManager.GetString("Common_EmailProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Sent.
        /// </summary>
        internal static string Common_EmailSent {
            get {
                return ResourceManager.GetString("Common_EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email was successfully sent to .
        /// </summary>
        internal static string Common_EmailSentTo {
            get {
                return ResourceManager.GetString("Common_EmailSentTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid Email address.
        /// </summary>
        internal static string Common_EnterValidEmail {
            get {
                return ResourceManager.GetString("Common_EnterValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Address.
        /// </summary>
        internal static string Common_InvalidEmail {
            get {
                return ResourceManager.GetString("Common_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your name..
        /// </summary>
        internal static string Common_NameRequired {
            get {
                return ResourceManager.GetString("Common_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string Common_No {
            get {
                return ResourceManager.GetString("Common_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Mismatch.
        /// </summary>
        internal static string Common_PasswordMismatch {
            get {
                return ResourceManager.GetString("Common_PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match. Please re-enter your password and confirm it..
        /// </summary>
        internal static string Common_PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("Common_PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Denied.
        /// </summary>
        internal static string Common_PermissionDenied {
            get {
                return ResourceManager.GetString("Common_PermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your phone number..
        /// </summary>
        internal static string Common_PhoneNumberRequired {
            get {
                return ResourceManager.GetString("Common_PhoneNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a country..
        /// </summary>
        internal static string Common_SelectCountry {
            get {
                return ResourceManager.GetString("Common_SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending data....
        /// </summary>
        internal static string Common_SendingData {
            get {
                return ResourceManager.GetString("Common_SendingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Common_Yes {
            get {
                return ResourceManager.GetString("Common_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your telephone provider settings have been successfully imported..
        /// </summary>
        internal static string Configruation_ProviderSettingsLoaded {
            get {
                return ResourceManager.GetString("Configruation_ProviderSettingsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This CallButler configuration file appears to be invalid and cannot be loaded..
        /// </summary>
        internal static string Configruation_UnableToLoad {
            get {
                return ResourceManager.GetString("Configruation_UnableToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-on Module Settings.
        /// </summary>
        internal static string DepartmentForm_AddonModuleSettings {
            get {
                return ResourceManager.GetString("DepartmentForm_AddonModuleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension Settings.
        /// </summary>
        internal static string DepartmentForm_ExtensionSettings {
            get {
                return ResourceManager.GetString("DepartmentForm_ExtensionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Settings.
        /// </summary>
        internal static string DepartmentForm_MessageSettings {
            get {
                return ResourceManager.GetString("DepartmentForm_MessageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Settings.
        /// </summary>
        internal static string DepartmentForm_NumberSettings {
            get {
                return ResourceManager.GetString("DepartmentForm_NumberSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script Settings.
        /// </summary>
        internal static string DepartmentForm_ScriptSettings {
            get {
                return ResourceManager.GetString("DepartmentForm_ScriptSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A test Email was successfully sent to {0}
        ///
        ///Check your Email in a few minutes to confirm the receipt of this message..
        /// </summary>
        internal static string EmailUtils_EmailSuccess {
            get {
                return ResourceManager.GetString("EmailUtils_EmailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a test message sent by CallButler.
        ///
        ///If you received this Email, your SMTP Email settings are correct..
        /// </summary>
        internal static string EmailUtils_TestEmail {
            get {
                return ResourceManager.GetString("EmailUtils_TestEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CallButler Test Message.
        /// </summary>
        internal static string EmailUtils_TestEmailSubject {
            get {
                return ResourceManager.GetString("EmailUtils_TestEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact your administrator.
        /// </summary>
        internal static string ExtensionEditorForm_ContactAdmin {
            get {
                return ResourceManager.GetString("ExtensionEditorForm_ContactAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Configuration.
        /// </summary>
        internal static string ExtensionEditorForm_EmailConfiguration {
            get {
                return ResourceManager.GetString("ExtensionEditorForm_EmailConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before sending Emails, CallButler must be configured for your SMTP Email Server.
        ///
        ///Would you like to do this now?.
        /// </summary>
        internal static string ExtensionEditorForm_EnterSMTP {
            get {
                return ResourceManager.GetString("ExtensionEditorForm_EnterSMTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify an Email address to which to send this Email.
        /// </summary>
        internal static string ExtensionEditorForm_PleaseSpecifyEmail {
            get {
                return ResourceManager.GetString("ExtensionEditorForm_PleaseSpecifyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new telephone extension.
        /// </summary>
        internal static string ExtensionEditorForm_YourNewExtension {
            get {
                return ResourceManager.GetString("ExtensionEditorForm_YourNewExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version of CallButler does not allow more than {0} extensions.
        ///If you would like to add more extensions, you may need to upgrade..
        /// </summary>
        internal static string ExtensionsView_ExtLimit {
            get {
                return ResourceManager.GetString("ExtensionsView_ExtLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete this extension?
        ///
        ///This will also delete any voicemail boxes associated with this extension..
        /// </summary>
        internal static string ExtensionView_ConfirmDelete {
            get {
                return ResourceManager.GetString("ExtensionView_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension Number Conflict.
        /// </summary>
        internal static string ExtensionView_ExtConflict {
            get {
                return ResourceManager.GetString("ExtensionView_ExtConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The extension number {0} is already taken. This extension number has been changed to {1} for you..
        /// </summary>
        internal static string ExtensionView_ExtTaken {
            get {
                return ResourceManager.GetString("ExtensionView_ExtTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retreiving sounds....
        /// </summary>
        internal static string GreetingUtils_GettingSounds {
            get {
                return ResourceManager.GetString("GreetingUtils_GettingSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving sounds....
        /// </summary>
        internal static string GreetingUtils_SavingSounds {
            get {
                return ResourceManager.GetString("GreetingUtils_SavingSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username and/or password you have specified is invalid. Please try again. .
        /// </summary>
        internal static string LoginForm_InvalidLogin {
            get {
                return ResourceManager.GetString("LoginForm_InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Login.
        /// </summary>
        internal static string LoginForm_InvalidLoginTitle {
            get {
                return ResourceManager.GetString("LoginForm_InvalidLoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password you entered appears to be incorrect.
        ///
        ///Please try again..
        /// </summary>
        internal static string MainForm_BadPassword {
            get {
                return ResourceManager.GetString("MainForm_BadPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CallButler Service.
        /// </summary>
        internal static string MainForm_CallButlerService {
            get {
                return ResourceManager.GetString("MainForm_CallButlerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes saved.
        /// </summary>
        internal static string MainForm_ChangesSaved {
            get {
                return ResourceManager.GetString("MainForm_ChangesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to turn on expert mode?
        ///
        ///Expert mode should only be used by advanced users and may temporarily disable CallButler from answering calls.
        ///    .
        /// </summary>
        internal static string MainForm_ChangeToExpertMode {
            get {
                return ResourceManager.GetString("MainForm_ChangeToExpertMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change to Expert Mode?.
        /// </summary>
        internal static string MainForm_ChangeToExpertModeCaption {
            get {
                return ResourceManager.GetString("MainForm_ChangeToExpertModeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to {0}.
        /// </summary>
        internal static string MainForm_ConnectedTo {
            get {
                return ResourceManager.GetString("MainForm_ConnectedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to {0}.
        /// </summary>
        internal static string MainForm_ConnectingTo {
            get {
                return ResourceManager.GetString("MainForm_ConnectingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered an invalid license key. Please try again..
        /// </summary>
        internal static string MainForm_EnteredBadLicense {
            get {
                return ResourceManager.GetString("MainForm_EnteredBadLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have enetered an expired trial license. Please try again..
        /// </summary>
        internal static string MainForm_EnteredExpiredLicense {
            get {
                return ResourceManager.GetString("MainForm_EnteredExpiredLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This trial version of CallButler has expired and will no longer answer calls.
        /// </summary>
        internal static string MainForm_Expired {
            get {
                return ResourceManager.GetString("MainForm_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This trial license will expire on {0}.
        /// </summary>
        internal static string MainForm_ExpireOnDate {
            get {
                return ResourceManager.GetString("MainForm_ExpireOnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This trial license for CallButler will expire in {0} day(s).
        /// </summary>
        internal static string MainForm_Expires {
            get {
                return ResourceManager.GetString("MainForm_Expires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid License Key.
        /// </summary>
        internal static string MainForm_InvalidLicenseKey {
            get {
                return ResourceManager.GetString("MainForm_InvalidLicenseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Validated.
        /// </summary>
        internal static string MainForm_LicenseValidated {
            get {
                return ResourceManager.GetString("MainForm_LicenseValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading data....
        /// </summary>
        internal static string MainForm_LoadingData {
            get {
                return ResourceManager.GetString("MainForm_LoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection.
        /// </summary>
        internal static string MainForm_NoConnection {
            get {
                return ResourceManager.GetString("MainForm_NoConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CallButler Service you are connecting to does not allow management from remote computers..
        /// </summary>
        internal static string MainForm_RemoteManagementError {
            get {
                return ResourceManager.GetString("MainForm_RemoteManagementError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Management Error.
        /// </summary>
        internal static string MainForm_RemoteManagementErrorCaption {
            get {
                return ResourceManager.GetString("MainForm_RemoteManagementErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving changes....
        /// </summary>
        internal static string MainForm_SavingChanges {
            get {
                return ResourceManager.GetString("MainForm_SavingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CallButler Service does not appear to be installed on this computer.
        ///
        ///If it is installed, you may need to start the service manually..
        /// </summary>
        internal static string MainForm_ServiceNotFound {
            get {
                return ResourceManager.GetString("MainForm_ServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CallButler Service does not appear to be running on this computer.
        ///
        ///Would you like to start the CallButler Service?.
        /// </summary>
        internal static string MainForm_ServiceNotRunning {
            get {
                return ResourceManager.GetString("MainForm_ServiceNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting the CallButler Service.
        /// </summary>
        internal static string MainForm_StartingService {
            get {
                return ResourceManager.GetString("MainForm_StartingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for registering this copy of CallButler..
        /// </summary>
        internal static string MainForm_ThankYouForReg {
            get {
                return ResourceManager.GetString("MainForm_ThankYouForReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial License.
        /// </summary>
        internal static string MainForm_TrialLicense {
            get {
                return ResourceManager.GetString("MainForm_TrialLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CallButler service you are trying to connect to is not available.
        ///
        ///Please check to make sure the server name or IP address is correct and try again..
        /// </summary>
        internal static string MainForm_UnableToConnect {
            get {
                return ResourceManager.GetString("MainForm_UnableToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CallButler User Manual does not appear to be installed on this computer..
        /// </summary>
        internal static string MainForm_UnableToFindUserManual {
            get {
                return ResourceManager.GetString("MainForm_UnableToFindUserManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for CallButler Service to start..
        /// </summary>
        internal static string MainForm_WaitingForService {
            get {
                return ResourceManager.GetString("MainForm_WaitingForService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the selected hold music?.
        /// </summary>
        internal static string MusicSettings_ConfirmRemoveMusic {
            get {
                return ResourceManager.GetString("MusicSettings_ConfirmRemoveMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this call personalization?.
        /// </summary>
        internal static string PersonalizedGreetingView_ConfirmDelete {
            get {
                return ResourceManager.GetString("PersonalizedGreetingView_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Finish.
        /// </summary>
        internal static string PrebuiltConfigForm_Finish {
            get {
                return ResourceManager.GetString("PrebuiltConfigForm_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Next &gt;.
        /// </summary>
        internal static string PrebuiltConfigForm_Next {
            get {
                return ResourceManager.GetString("PrebuiltConfigForm_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        internal static string Program_Initializing {
            get {
                return ResourceManager.GetString("Program_Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this provider?.
        /// </summary>
        internal static string ProvidersView_ConfirmDelete {
            get {
                return ResourceManager.GetString("ProvidersView_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Receptionist.
        /// </summary>
        internal static string Receptionist_IsReceptionist {
            get {
                return ResourceManager.GetString("Receptionist_IsReceptionist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Error.
        /// </summary>
        internal static string ReportPrinter_PrintError {
            get {
                return ResourceManager.GetString("ReportPrinter_PrintError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to print report.
        ///
        ///.
        /// </summary>
        internal static string ReportPrinter_UnableToPrint {
            get {
                return ResourceManager.GetString("ReportPrinter_UnableToPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to delete this script schedule?.
        /// </summary>
        internal static string ScriptScheduleView_ConfirmDelete {
            get {
                return ResourceManager.GetString("ScriptScheduleView_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Script Schedule.
        /// </summary>
        internal static string ScriptScheduleView_NewSchedule {
            get {
                return ResourceManager.GetString("ScriptScheduleView_NewSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading music...
        ///This may take a few moments..
        /// </summary>
        internal static string SettingsView_UploadingMusic {
            get {
                return ResourceManager.GetString("SettingsView_UploadingMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Caller.
        /// </summary>
        internal static string SummaryView_UnkownCaller {
            get {
                return ResourceManager.GetString("SummaryView_UnkownCaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Transfer.
        /// </summary>
        internal static string TestDriveView_CallTransfer {
            get {
                return ResourceManager.GetString("TestDriveView_CallTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CallButler Test Call.
        /// </summary>
        internal static string TestDriveView_CBTestCall {
            get {
                return ResourceManager.GetString("TestDriveView_CBTestCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string TestDriveView_Connected {
            get {
                return ResourceManager.GetString("TestDriveView_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the call button to begin....
        /// </summary>
        internal static string TestDriveView_PressToCall {
            get {
                return ResourceManager.GetString("TestDriveView_PressToCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready for Call.
        /// </summary>
        internal static string TestDriveView_ReadyForCall {
            get {
                return ResourceManager.GetString("TestDriveView_ReadyForCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This call would now be transferred to {0} but this test cannot simulate that.
        ///
        ///The call will now hang up..
        /// </summary>
        internal static string TestDriveView_TransferSim {
            get {
                return ResourceManager.GetString("TestDriveView_TransferSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new version of CallButler has been downloaded.
        ///
        ///Would you like to install this new version now?.
        /// </summary>
        internal static string VersionCheckeForm_FinishedDownload {
            get {
                return ResourceManager.GetString("VersionCheckeForm_FinishedDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Complete.
        /// </summary>
        internal static string VersionCheckerForm_DownloadComplete {
            get {
                return ResourceManager.GetString("VersionCheckerForm_DownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Error.
        /// </summary>
        internal static string VersionCheckerForm_DownloadError {
            get {
                return ResourceManager.GetString("VersionCheckerForm_DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading the latest version of CallButler.
        /// </summary>
        internal static string VersionCheckerForm_Downloading {
            get {
                return ResourceManager.GetString("VersionCheckerForm_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not running the latest version of CallButler.
        ///We recommend that you download the latest version..
        /// </summary>
        internal static string VersionCheckerForm_NotOnLatest {
            get {
                return ResourceManager.GetString("VersionCheckerForm_NotOnLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem downloading the new version of CallButler. Please contact support@callbutler.com..
        /// </summary>
        internal static string VersionCheckerForm_ProblemDownloading {
            get {
                return ResourceManager.GetString("VersionCheckerForm_ProblemDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are running the latest version of CallButler..
        /// </summary>
        internal static string VersionCheckerForm_RunningLatest {
            get {
                return ResourceManager.GetString("VersionCheckerForm_RunningLatest", resourceCulture);
            }
        }
    }
}
