//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallButler.Manager.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CallButler.Manager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap about_16 {
            get {
                object obj = ResourceManager.GetObject("about_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap about_32 {
            get {
                object obj = ResourceManager.GetObject("about_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_down_blue_16 {
            get {
                object obj = ResourceManager.GetObject("arrow_down_blue_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_up_blue_16 {
            get {
                object obj = ResourceManager.GetObject("arrow_up_blue_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap back_down {
            get {
                object obj = ResourceManager.GetObject("back_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap back_up {
            get {
                object obj = ResourceManager.GetObject("back_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap branch_16 {
            get {
                object obj = ResourceManager.GetObject("branch_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap branch_24 {
            get {
                object obj = ResourceManager.GetObject("branch_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap branch_48_shadow {
            get {
                object obj = ResourceManager.GetObject("branch_48_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cabinet_16 {
            get {
                object obj = ResourceManager.GetObject("cabinet_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cabinet_32_shadow {
            get {
                object obj = ResourceManager.GetObject("cabinet_32_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap call_greeting_24 {
            get {
                object obj = ResourceManager.GetObject("call_greeting_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1033\deflangfe1033{\fonttbl{\f0\froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f3\froman\fcharset2\fprq2{\*\panose 05050102010706020507}Symbol;}
        ///{\f36\fswiss\fcharset0\fprq2{\*\panose 020b0604030504040204}Tahoma;}{\f43\fswiss\fcharset0\fprq2{\*\panose 020b0604030504040204}Verdana;}{\f149\froman\fcharset238\fprq2 Times New Roman CE;}{\f150\froman\fcharset204\fprq2 Times New Roman  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CallFlowHelp {
            get {
                return ResourceManager.GetString("CallFlowHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1033\deflangfe1033{\fonttbl{\f0\froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f3\froman\fcharset2\fprq2{\*\panose 05050102010706020507}Symbol;}
        ///{\f36\fswiss\fcharset0\fprq2{\*\panose 020b0604030504040204}Tahoma;}{\f43\fswiss\fcharset0\fprq2{\*\panose 020b0604030504040204}Verdana;}{\f149\froman\fcharset238\fprq2 Times New Roman CE;}{\f150\froman\fcharset204\fprq2 Times New Roman  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CallPersonalizationHelp {
            get {
                return ResourceManager.GetString("CallPersonalizationHelp", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap cb_header {
            get {
                object obj = ResourceManager.GetObject("cb_header", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cb_header_small {
            get {
                object obj = ResourceManager.GetObject("cb_header_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap column_chart_24 {
            get {
                object obj = ResourceManager.GetObject("column_chart_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap connection_16 {
            get {
                object obj = ResourceManager.GetObject("connection_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap date_time_16 {
            get {
                object obj = ResourceManager.GetObject("date_time_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap date_time_24 {
            get {
                object obj = ResourceManager.GetObject("date_time_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap date_time_48_shadow {
            get {
                object obj = ResourceManager.GetObject("date_time_48_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delete_16 {
            get {
                object obj = ResourceManager.GetObject("delete_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap disk_blue_16 {
            get {
                object obj = ResourceManager.GetObject("disk_blue_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap disk_blue_161 {
            get {
                object obj = ResourceManager.GetObject("disk_blue_161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap divider_line {
            get {
                object obj = ResourceManager.GetObject("divider_line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap download_16 {
            get {
                object obj = ResourceManager.GetObject("download_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap earth_add_16 {
            get {
                object obj = ResourceManager.GetObject("earth_add_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap earth_connection_48_shadow {
            get {
                object obj = ResourceManager.GetObject("earth_connection_48_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap earth_network_16 {
            get {
                object obj = ResourceManager.GetObject("earth_network_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap earth_network_32_shadow {
            get {
                object obj = ResourceManager.GetObject("earth_network_32_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap earth2_16 {
            get {
                object obj = ResourceManager.GetObject("earth2_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap earth2_32_shadow {
            get {
                object obj = ResourceManager.GetObject("earth2_32_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap error_16 {
            get {
                object obj = ResourceManager.GetObject("error_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1033\deflangfe1033{\fonttbl{\f0\froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f36\fswiss\fcharset0\fprq2{\*\panose 020b0604030504040204}Tahoma;}{\f149\froman\fcharset238\fprq2 Times New Roman CE;}
        ///{\f150\froman\fcharset204\fprq2 Times New Roman Cyr;}{\f152\froman\fcharset161\fprq2 Times New Roman Greek;}{\f153\froman\fcharset162\fprq2 Times New Roman Tur;}{\f154\fbidi \froman\fc [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ExtensionsHelp {
            get {
                return ResourceManager.GetString("ExtensionsHelp", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap flag_checkered_16 {
            get {
                object obj = ResourceManager.GetObject("flag_checkered_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flag_checkered_48_shadow {
            get {
                object obj = ResourceManager.GetObject("flag_checkered_48_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flag_green_16 {
            get {
                object obj = ResourceManager.GetObject("flag_green_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flag_green_48_shadow {
            get {
                object obj = ResourceManager.GetObject("flag_green_48_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_16 {
            get {
                object obj = ResourceManager.GetObject("folder_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_music_16 {
            get {
                object obj = ResourceManager.GetObject("folder_music_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gauge_128_shadow {
            get {
                object obj = ResourceManager.GetObject("gauge_128_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gauge_16 {
            get {
                object obj = ResourceManager.GetObject("gauge_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gauge_24 {
            get {
                object obj = ResourceManager.GetObject("gauge_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gauge_48_shadow {
            get {
                object obj = ResourceManager.GetObject("gauge_48_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gear_connection_24 {
            get {
                object obj = ResourceManager.GetObject("gear_connection_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gear_connection_48 {
            get {
                object obj = ResourceManager.GetObject("gear_connection_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gear_find_48_shadow {
            get {
                object obj = ResourceManager.GetObject("gear_find_48_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gear_information_32 {
            get {
                object obj = ResourceManager.GetObject("gear_information_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hand_offer_16 {
            get {
                object obj = ResourceManager.GetObject("hand_offer_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hand_offer_32_shadow {
            get {
                object obj = ResourceManager.GetObject("hand_offer_32_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hand_offer_48 {
            get {
                object obj = ResourceManager.GetObject("hand_offer_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap help_16 {
            get {
                object obj = ResourceManager.GetObject("help_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap help2_32 {
            get {
                object obj = ResourceManager.GetObject("help2_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap history2_shadow_42 {
            get {
                object obj = ResourceManager.GetObject("history2_shadow_42", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap id_card_24 {
            get {
                object obj = ResourceManager.GetObject("id_card_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap id_card_32_shadow {
            get {
                object obj = ResourceManager.GetObject("id_card_32_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap import_16 {
            get {
                object obj = ResourceManager.GetObject("import_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap import1 {
            get {
                object obj = ResourceManager.GetObject("import1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap information {
            get {
                object obj = ResourceManager.GetObject("information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap keys_16 {
            get {
                object obj = ResourceManager.GetObject("keys_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap keys_32_shadow {
            get {
                object obj = ResourceManager.GetObject("keys_32_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lock_16 {
            get {
                object obj = ResourceManager.GetObject("lock_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lock_32_shadow {
            get {
                object obj = ResourceManager.GetObject("lock_32_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap loudspeaker_16 {
            get {
                object obj = ResourceManager.GetObject("loudspeaker_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap loudspeaker_32_shadow {
            get {
                object obj = ResourceManager.GetObject("loudspeaker_32_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mail_earth_16 {
            get {
                object obj = ResourceManager.GetObject("mail_earth_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mail_earth_32_shadow {
            get {
                object obj = ResourceManager.GetObject("mail_earth_32_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mailbox_full_16 {
            get {
                object obj = ResourceManager.GetObject("mailbox_full_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mailbox_full_24 {
            get {
                object obj = ResourceManager.GetObject("mailbox_full_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mailbox_full_48_shadow {
            get {
                object obj = ResourceManager.GetObject("mailbox_full_48_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_play_16 {
            get {
                object obj = ResourceManager.GetObject("media_play_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_record_red_16 {
            get {
                object obj = ResourceManager.GetObject("media_record_red_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_step_back_16 {
            get {
                object obj = ResourceManager.GetObject("media_step_back_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_step_forward_16 {
            get {
                object obj = ResourceManager.GetObject("media_step_forward_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap media_stop_red_16 {
            get {
                object obj = ResourceManager.GetObject("media_stop_red_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap microphone2_16 {
            get {
                object obj = ResourceManager.GetObject("microphone2_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap music_16 {
            get {
                object obj = ResourceManager.GetObject("music_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap music_32_shadow {
            get {
                object obj = ResourceManager.GetObject("music_32_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap navigate_left_16 {
            get {
                object obj = ResourceManager.GetObject("navigate_left_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap navigate_left2_16 {
            get {
                object obj = ResourceManager.GetObject("navigate_left2_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap navigate_right_16 {
            get {
                object obj = ResourceManager.GetObject("navigate_right_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap navigate_right2_16 {
            get {
                object obj = ResourceManager.GetObject("navigate_right2_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap node_24 {
            get {
                object obj = ResourceManager.GetObject("node_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap node_48_shadow {
            get {
                object obj = ResourceManager.GetObject("node_48_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nut_and_bolt_16 {
            get {
                object obj = ResourceManager.GetObject("nut_and_bolt_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nut_and_bolt_24 {
            get {
                object obj = ResourceManager.GetObject("nut_and_bolt_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nut_and_bolt_48_shadow {
            get {
                object obj = ResourceManager.GetObject("nut_and_bolt_48_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap office_24 {
            get {
                object obj = ResourceManager.GetObject("office_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap office_building_128_shadow {
            get {
                object obj = ResourceManager.GetObject("office_building_128_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap office_building_48_shadow {
            get {
                object obj = ResourceManager.GetObject("office_building_48_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap office_chair_24 {
            get {
                object obj = ResourceManager.GetObject("office_chair_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap office_chair_48_shadow {
            get {
                object obj = ResourceManager.GetObject("office_chair_48_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap oszillograph_16 {
            get {
                object obj = ResourceManager.GetObject("oszillograph_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap oszillograph_32_shadow {
            get {
                object obj = ResourceManager.GetObject("oszillograph_32_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap outlook_16 {
            get {
                object obj = ResourceManager.GetObject("outlook_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap outlook_32 {
            get {
                object obj = ResourceManager.GetObject("outlook_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Phone_back_down {
            get {
                object obj = ResourceManager.GetObject("Phone_back_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phone_back_up {
            get {
                object obj = ResourceManager.GetObject("phone_back_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phone_button_24 {
            get {
                object obj = ResourceManager.GetObject("phone_button_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phone_conference_16 {
            get {
                object obj = ResourceManager.GetObject("phone_conference_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phone_conference_48_shadow {
            get {
                object obj = ResourceManager.GetObject("phone_conference_48_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phone_hang_up_24 {
            get {
                object obj = ResourceManager.GetObject("phone_hang_up_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phone_pick_up_24 {
            get {
                object obj = ResourceManager.GetObject("phone_pick_up_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phone_pick_up_48 {
            get {
                object obj = ResourceManager.GetObject("phone_pick_up_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap phone_redirect_128_shadow {
            get {
                object obj = ResourceManager.GetObject("phone_redirect_128_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap photo_scenery_16 {
            get {
                object obj = ResourceManager.GetObject("photo_scenery_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap plug_32_shadow {
            get {
                object obj = ResourceManager.GetObject("plug_32_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap plug_delete_48_shadow {
            get {
                object obj = ResourceManager.GetObject("plug_delete_48_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap printer {
            get {
                object obj = ResourceManager.GetObject("printer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap provider_connection_24 {
            get {
                object obj = ResourceManager.GetObject("provider_connection_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1033\deflangfe1033{\fonttbl{\f0\froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f3\froman\fcharset2\fprq2{\*\panose 05050102010706020507}Symbol;}
        ///{\f36\fswiss\fcharset0\fprq2{\*\panose 020b0604030504040204}Tahoma;}{\f43\fswiss\fcharset0\fprq2{\*\panose 020b0604030504040204}Verdana;}{\f149\froman\fcharset238\fprq2 Times New Roman CE;}{\f150\froman\fcharset204\fprq2 Times New Roman  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ProviderHelp {
            get {
                return ResourceManager.GetString("ProviderHelp", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap refresh_16 {
            get {
                object obj = ResourceManager.GetObject("refresh_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1033\deflangfe1033{\fonttbl{\f0\froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f3\froman\fcharset2\fprq2{\*\panose 05050102010706020507}Symbol;}
        ///{\f36\fswiss\fcharset0\fprq2{\*\panose 020b0604030504040204}Tahoma;}{\f43\fswiss\fcharset0\fprq2{\*\panose 020b0604030504040204}Verdana;}{\f149\froman\fcharset238\fprq2 Times New Roman CE;}{\f150\froman\fcharset204\fprq2 Times New Roman  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ScriptScheduleHelp {
            get {
                return ResourceManager.GetString("ScriptScheduleHelp", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap scroll_24 {
            get {
                object obj = ResourceManager.GetObject("scroll_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap select_all_16 {
            get {
                object obj = ResourceManager.GetObject("select_all_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap select_inverse_16 {
            get {
                object obj = ResourceManager.GetObject("select_inverse_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap select_none_16 {
            get {
                object obj = ResourceManager.GetObject("select_none_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shoppingcart_full_16 {
            get {
                object obj = ResourceManager.GetObject("shoppingcart_full_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sportscar_24 {
            get {
                object obj = ResourceManager.GetObject("sportscar_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sportscar_48_shadow {
            get {
                object obj = ResourceManager.GetObject("sportscar_48_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap step_127_shadow {
            get {
                object obj = ResourceManager.GetObject("step_127_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stopwatch_16 {
            get {
                object obj = ResourceManager.GetObject("stopwatch_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap t2logo {
            get {
                object obj = ResourceManager.GetObject("t2logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap telephone_16 {
            get {
                object obj = ResourceManager.GetObject("telephone_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap telephone_24 {
            get {
                object obj = ResourceManager.GetObject("telephone_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap telephone_48_shadow {
            get {
                object obj = ResourceManager.GetObject("telephone_48_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1033\deflangfe1033{\fonttbl{\f0\froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f3\froman\fcharset2\fprq2{\*\panose 05050102010706020507}Symbol;}
        ///{\f36\fswiss\fcharset0\fprq2{\*\panose 020b0604030504040204}Tahoma;}{\f43\fswiss\fcharset0\fprq2{\*\panose 020b0604030504040204}Verdana;}{\f149\froman\fcharset238\fprq2 Times New Roman CE;}{\f150\froman\fcharset204\fprq2 Times New Roman  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string TestDriveHelp {
            get {
                return ResourceManager.GetString("TestDriveHelp", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap text_loudspeaker_16 {
            get {
                object obj = ResourceManager.GetObject("text_loudspeaker_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap text_loudspeaker_32_shadow {
            get {
                object obj = ResourceManager.GetObject("text_loudspeaker_32_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbox_16 {
            get {
                object obj = ResourceManager.GetObject("toolbox_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbox_24 {
            get {
                object obj = ResourceManager.GetObject("toolbox_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbox_48_shadow {
            get {
                object obj = ResourceManager.GetObject("toolbox_48_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap trafficlight_on_48_shadow {
            get {
                object obj = ResourceManager.GetObject("trafficlight_on_48_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user1_message_32_shadow {
            get {
                object obj = ResourceManager.GetObject("user1_message_32_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user1_mobilephone_128_shadow {
            get {
                object obj = ResourceManager.GetObject("user1_mobilephone_128_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user1_telephone_16 {
            get {
                object obj = ResourceManager.GetObject("user1_telephone_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user1_telephone_24 {
            get {
                object obj = ResourceManager.GetObject("user1_telephone_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user1_telephone_48_shadow {
            get {
                object obj = ResourceManager.GetObject("user1_telephone_48_shadow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_16 {
            get {
                object obj = ResourceManager.GetObject("view_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_previous_16 {
            get {
                object obj = ResourceManager.GetObject("view_previous_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap voip_service_logo {
            get {
                object obj = ResourceManager.GetObject("voip_service_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap window_error_16 {
            get {
                object obj = ResourceManager.GetObject("window_error_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap windows_16 {
            get {
                object obj = ResourceManager.GetObject("windows_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap wizard_header {
            get {
                object obj = ResourceManager.GetObject("wizard_header", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
