//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallButler.Manager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string CallButlerServer {
            get {
                return ((string)(this["CallButlerServer"]));
            }
            set {
                this["CallButlerServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int CustomerID {
            get {
                return ((int)(this["CustomerID"]));
            }
            set {
                this["CustomerID"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public short MinExtensionNumber {
            get {
                return ((short)(this["MinExtensionNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Sounds\\Greetings Cache")]
        public string GreetingsSoundCache {
            get {
                return ((string)(this["GreetingsSoundCache"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RecentServers {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentServers"]));
            }
            set {
                this["RecentServers"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30872")]
        public int TcpManagementPort {
            get {
                return ((int)(this["TcpManagementPort"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Sounds\\Voicemails Cache")]
        public string VoicemailSoundCache {
            get {
                return ((string)(this["VoicemailSoundCache"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayCommonTasks {
            get {
                return ((bool)(this["DisplayCommonTasks"]));
            }
            set {
                this["DisplayCommonTasks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ManagementPassword {
            get {
                return ((string)(this["ManagementPassword"]));
            }
            set {
                this["ManagementPassword"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.callbutler.com/Files/CallButler%20Message%20Center%20Setup.exe")]
        public string ExtensionClientDownloadURL {
            get {
                return ((string)(this["ExtensionClientDownloadURL"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ApplicationVersion {
            get {
                return ((string)(this["ApplicationVersion"]));
            }
            set {
                this["ApplicationVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpdateNotification {
            get {
                return ((bool)(this["UpdateNotification"]));
            }
            set {
                this["UpdateNotification"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.callbutler.com/")]
        public string SupportUrl {
            get {
                return ((string)(this["SupportUrl"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayShutdownDialog {
            get {
                return ((bool)(this["DisplayShutdownDialog"]));
            }
            set {
                this["DisplayShutdownDialog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Horizontal")]
        public global::Controls.Diagram.DiagramLayoutDirection CallFlowOrientation {
            get {
                return ((global::Controls.Diagram.DiagramLayoutDirection)(this["CallFlowOrientation"]));
            }
            set {
                this["CallFlowOrientation"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.callbutler.com/purchase/cart.aspx?ProductID=")]
        public string BuyLicenseURL {
            get {
                return ((string)(this["BuyLicenseURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Data\\Configs\\PrebuiltConfigCatalog.xml")]
        public string PrebuiltConfigCatalogPath {
            get {
                return ((string)(this["PrebuiltConfigCatalogPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Data\\Configs\\")]
        public string PrebuiltConfigDataPath {
            get {
                return ((string)(this["PrebuiltConfigDataPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Plugins")]
        public string PluginsPath {
            get {
                return ((string)(this["PluginsPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Local")]
        public global::CallButler.ManagementInterface.CallButlerManagementInterfaceType ManagementInterfaceType {
            get {
                return ((global::CallButler.ManagementInterface.CallButlerManagementInterfaceType)(this["ManagementInterfaceType"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PreviousLogin {
            get {
                return ((string)(this["PreviousLogin"]));
            }
            set {
                this["PreviousLogin"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B9E75DC5-3B47-49bd-8D61-1628889104BB")]
        public string PreferredVoIPProviderPluginID {
            get {
                return ((string)(this["PreferredVoIPProviderPluginID"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("B9E75DC5-3B47-49bd-8D61-1628889104BB")]
        public string DefaultVoIPProviderPluginID {
            get {
                return ((string)(this["DefaultVoIPProviderPluginID"]));
            }
            set {
                this["DefaultVoIPProviderPluginID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fe858d01-1ac7-46cc-817b-b206702440f9")]
        public string DefaultFindMePluginID {
            get {
                return ((string)(this["DefaultFindMePluginID"]));
            }
            set {
                this["DefaultFindMePluginID"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.callbutler.com/about/features.aspx")]
        public string EditionCompareURL {
            get {
                return ((string)(this["EditionCompareURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\..\\Help\\CallButler User Manual.chm")]
        public string UserManualPath {
            get {
                return ((string)(this["UserManualPath"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UICulture {
            get {
                return ((string)(this["UICulture"]));
            }
            set {
                this["UICulture"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.callbutler.com/modules")]
        public string ModulesDownloadURL {
            get {
                return ((string)(this["ModulesDownloadURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
Dear User,

A new CallButler telephone system has been installed in your organization and you have been assigned a telephone Extension. This telephone extension will allow callers to leave voicemail messages and to optionally find and connect to you on your office, mobile or home phone.

----------------------------------------------------------------
You new extension number is:		#ExtNumber#
You new extension passcode is:	#ExtPasscode#
----------------------------------------------------------------

To listen to your voicemail and change your voicemail greeting.

1) From an outside line: Dial your organization's main telephone number.
   When you hear the main menu, dial your extension number.
   
   From an inside line: Dial your extension number.

2) Press the * key on your telephone.
3) When asked for you passcode, dial #ExtPasscode#.

For additional help, please contact your administrator.")]
        public string ExtensionClientSetupMail {
            get {
                return ((string)(this["ExtensionClientSetupMail"]));
            }
        }
    }
}
