//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallButler.Service.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CallButler.Service.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap exit_16 {
            get {
                object obj = ResourceManager.GetObject("exit_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;link href=&quot;http://www.callbutler.com/StyleSheet.css&quot; rel=&quot;stylesheet&quot; type=&quot;text/css&quot; /&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///		.actionButtonLarge, a:link.actionButtonLarge, a:visited.actionButtonLarge, input.submit
        ///{
        ///	display:-moz-inline-box;
        ///	-moz-box-pack: center;
        ///	display: inline-block;
        ///	vertical-align: mid [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string FreeInfo {
            get {
                return ResourceManager.GetString("FreeInfo", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap gear_connection_16 {
            get {
                object obj = ResourceManager.GetObject("gear_connection_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nut_and_bolt_16 {
            get {
                object obj = ResourceManager.GetObject("nut_and_bolt_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;AppPermissionsData xmlns=&quot;http://tempuri.org/AppPermissionsData.xsd&quot;&gt;
        ///  &lt;AppPermissions&gt;
        ///    &lt;PermissionID&gt;0&lt;/PermissionID&gt;
        ///    &lt;PermissionName&gt;ConnectRemote&lt;/PermissionName&gt;
        ///  &lt;/AppPermissions&gt;
        ///  &lt;AppPermissions&gt;
        ///    &lt;PermissionID&gt;1&lt;/PermissionID&gt;
        ///    &lt;PermissionName&gt;ExpertMode&lt;/PermissionName&gt;
        ///    &lt;AppPermissionAssignments&gt;
        ///      &lt;PermissionID&gt;1&lt;/PermissionID&gt;
        ///      &lt;ProductID&gt;CB-SKYPEFREE-1&lt;/ProductID&gt;
        ///      &lt;IsPermitted&gt;false&lt;/IsPermitted&gt;
        ///      &lt;Scal [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream powered_by_16khz {
            get {
                return ResourceManager.GetStream("powered_by_16khz", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream powered_by_8khz {
            get {
                return ResourceManager.GetStream("powered_by_8khz", resourceCulture);
            }
        }
    }
}
