regsvr32 ToneEncoder.dll
regsvr32 NCTAudioPlayer2.dll
regsvr32 secman.dll
regsvr32 WOSISpAudio.dll
regsvr32 Interop.NCTAUDIOCOMPRESS2Lib.dll
regsvr32 WOSI.NET.RTP.dll
regsvr32 Interop.NCTAUDIOPLAYER2Lib.dll
regsvr32 Interop.SpeechLib.dll
regsvr32 WOSI.Utilities.Sound.dll
regsvr32 WOSI.Controls.dll
regsvr32 WOSI.NET.inTELIPhone.dll
regsvr32 WaveExCtrl.dll
regsvr32 NCTAudioRecord2.dll
regsvr32 NCTAudioFile2.dll
regsvr32 WOSI.Utilities.SoundConversion.dll
regsvr32 ToneDecoder.dll
regsvr32 Interop.NCTAUDIORECORD2Lib.dll
regsvr32 NCTAudioInformation2.dll
regsvr32 Interop.NCTAUDIOFILE2Lib.dll
regsvr32 WOSI.IVR.IML.dll
regsvr32 NCTAudioCompress2.dll