regsvr32 /u ToneEncoder.dll
regsvr32 /u NCTAudioPlayer2.dll
regsvr32 /u secman.dll
regsvr32 /u WOSISpAudio.dll
regsvr32 /u Interop.NCTAUDIOCOMPRESS2Lib.dll
regsvr32 /u WOSI.NET.RTP.dll
regsvr32 /u Interop.NCTAUDIOPLAYER2Lib.dll
regsvr32 /u Interop.SpeechLib.dll
regsvr32 /u WOSI.Utilities.Sound.dll
regsvr32 /u WOSI.Controls.dll
regsvr32 /u WOSI.NET.inTELIPhone.dll
regsvr32 /u WaveExCtrl.dll
regsvr32 /u NCTAudioRecord2.dll
regsvr32 /u NCTAudioFile2.dll
regsvr32 /u WOSI.Utilities.SoundConversion.dll
regsvr32 /u ToneDecoder.dll
regsvr32 /u Interop.NCTAUDIORECORD2Lib.dll
regsvr32 /u NCTAudioInformation2.dll
regsvr32 /u Interop.NCTAUDIOFILE2Lib.dll
regsvr32 /u WOSI.IVR.IML.dll
regsvr32 /u NCTAudioCompress2.dll